### ISSUE TITLE
Why no "caption" and "credits" fields in semantics?

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#405]
I regret the absence of those two fields in h5p-ndla-timeline. They are available in the original timeline.knightlab libraries and very useful.

**Comment by janlindso** [comment]
We will discuss if "caption" should be included. Credits are already covered by the standard "Rights of use"-link at the bottom of the H5P.

**Comment by rezeau** [comment]
1.- For the media inserted by the _Media Type_: Image, Video, etc. elements Credits are indeed covered by the standard H5P Rights of use link 
2.- For the _External Links_ media items Credits are covered by the info entered in the NDLANO Edit Copyright field.
Unfortunately, the NDLANO Timeline Copyright Rights of Use popup window is not always displayed as expected, I mean it's often _truncated_, especially if the Timeline is not displayed full screen. This behaviour should be improved.
![2023-05-29_16-35-06](https://github.com/NDLANO/h5p-ndla-timeline/assets/503583/b017c5bc-87fd-4960-82e2-e43cf43c0a97)

**Comment by otacke** [comment]
@janlindso I can confirm that finding and wonder why this custom approach for handling copyright was chosen.

As you already mentioned, H5P offers the "Copyright" button that is supposed to present all the copyright information.
- One could have used the underlying mechanism to add the copyright information for text fields easily. There's `H5P.Text` and there's `H5P.AdvancedText` which could have been used as a normal `library` field, which would have supplied an HTML text field and the regular "metadata button" for the text, and H5P would have compiled the copyright information.
- One could have added a `getCopyrights` function to the content's main instance that would take precedence over the automated copyright field collection and allows to compile copyright information in a custom manner if required - and the return value would have been made available via the "Copyright" button as well.

Instead, a custom "Copyright" widget was created to add copyright information (which may have made sense, don't know the context), but instead of using the `getCopyrights` approach to also add that information, a custom copyright popup is injected into the DOM of Knightlab's Timeline - and it's cut off at the bottom if there's not enough vertical space as it's bound to its container's height.

At first sight (potentially not knowing all the context), I'd say that the whole copyright widget including the components for displaying the copyright popover would not have been necessary at all.

On top, I noticed that if one added information for some media including metadata and then decided to use some other medium, the copyright information is still held and displayed via the "Copyright" button. One should use the `nullWhenHidden` property in the `showWhen` widget (may not have been available when NDLA Timeline was created) - or one should have considered to implement the `getCopyright` function in order to filter out copyright information that is not actually used).

@janlindso Please let me know if you require the custom copyright popover and whether this is something that I (or maybe @rezeau) should work on.

**Comment by janlindso** [comment]
It's not really usual to have a caption or special copyright for embedded stuff. Why do we need it here @rezeau?
