### ISSUE TITLE
Why did you rename branch main to master?

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#423]
Not an issue as such, but I'm surprised you renamed branch "main" to "master" recently. This seems to go against the general recommended trend on github. See for example https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by otacke** [comment]
@rezeau One should not follow each and every trend blindly. NDLA chose `master`, because the idea is to make things less confusing: H5P Group is using `master`, so that's done here as well in order to not deviate from their way of naming branches. This will hopefully help less experienced developers to find their way around across different H5P repositories of different organizations. Another aspect is tooling. If you, for instance, built a github action that wants to pull from specific branches across different repositories, it makes sense if they are organized the same way.
